language: ruby

rvm:
  - jruby-19mode
  - jruby-head
  - rbx
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - gem install bundler -v '= 1.5.1'
